### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by k0pernikus** [ivelkov/teams-for-linux#21]
Using node8.9 I get an error when trying to run this via:

    npm install && npm start

It outputs this:

```
> teams-for-linux@0.0.4 start /home/philipp/teams-for-linux
> electron ./app

Gtk-Message: Failed to load module "overlay-scrollbar"
App threw an error during load
Error: Cannot find module 'open'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/philipp/teams-for-linux/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/philipp/teams-for-linux/app/lib/index.js:5:14)
    at Object.<anonymous> (/home/philipp/teams-for-linux/app/lib/index.js:57:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'open'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/philipp/teams-for-linux/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/philipp/teams-for-linux/app/lib/index.js:5:14)
    at Object.<anonymous> (/home/philipp/teams-for-linux/app/lib/index.js:57:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by julian-alarcon** [comment]
Check this fork and star it! https://github.com/IsmaelMartinez/teams-for-linux It is currently supported!

Maybe these issue is not there.
