### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by MrObvious** [ivelkov/teams-for-linux#35]
open("/usr/share/locale/en_US/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
futex(0x7fce2053ae28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/usr/share/locale/en_US/LC_MESSAGES/gtk20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/gtk20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/gtk20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/gtk20.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
futex(0x7fce1ec2a0c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/X11/locale/locale.alias", O_RDONLY) = 18
fstat(18, {st_mode=S_IFREG|0644, st_size=82750, ...}) = 0
read(18, "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"..., 4096) = 4096
read(18, "N.UTF-8\nbo_IN.utf8\t\t\t\t\tbo_IN.UTF"..., 4096) = 4096
read(18, "\t\t\t\t\tde_DE.ISO8859-15\nde_DE.8859"..., 4096) = 4096
read(18, "\t\t\t\ten_ZA.ISO8859-1\nen_ZA.88591."..., 4096) = 4096
read(18, "\t\t\t\t\t\teu_ES.ISO8859-1\neu_ES.iso8"..., 4096) = 4096
read(18, "iso88591\t\t\t\t\tgv_GB.ISO8859-1\ngv_"..., 4096) = 4096
read(18, "i\nkw\t\t\t\t\t\tkw_GB.ISO8859-1\nkw_GB\t"..., 4096) = 4096
read(18, "8859-15\nno@nynorsk\t\t\t\t\tny_NO.ISO"..., 4096) = 4096
read(18, "-8\nsr_YU@cyrillic\t\t\t\t\tsr_RS.UTF-"..., 4096) = 4096
read(18, "\t\t\tyi_US.CP1255\nyi_US.MICROSOFT-"..., 4096) = 4096
read(18, "d word is full locale name.\n#\n#\n"..., 4096) = 4096
read(18, "859-1\nbr_FR.iso88591:\t\t\t\t\tbr_FR."..., 4096) = 4096
read(18, "e_DE:\t\t\t\t\t\tde_DE.ISO8859-1\nde_DE"..., 4096) = 4096
read(18, "\t\t\t\t\ten_US.ISO8859-15\nen_US.ISO8"..., 4096) = 4096
read(18, "-1\net_EE.iso88594:\t\t\t\t\tet_EE.ISO"..., 4096) = 4096
read(18, "S.ISO8859-1\ngl_ES.iso88591:\t\t\t\t\t"..., 4096) = 4096
read(18, ".UTF-8\nkm_KH.utf8:\t\t\t\t\tkm_KH.UTF"..., 4096) = 4096
read(18, "SO8859-1\nno_NO.iso88591:\t\t\t\t\tno_"..., 4096) = 4096
read(18, "ET:                        sid_E"..., 4096) = 4096
read(18, "UZ.UTF-8\nuz_UZ.UTF-8@cyrillic:\t\t"..., 4096) = 4096
read(18, "_RO.ISO8859-2\nrumanian:\t\t\t\t\tro_R"..., 4096) = 830
read(18, "", 4096)                      = 0
close(18)                               = 0
openat(AT_FDCWD, "/usr/share/X11/locale/locale.alias", O_RDONLY) = 18
fstat(18, {st_mode=S_IFREG|0644, st_size=82750, ...}) = 0
read(18, "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"..., 4096) = 4096
read(18, "N.UTF-8\nbo_IN.utf8\t\t\t\t\tbo_IN.UTF"..., 4096) = 4096
read(18, "\t\t\t\t\tde_DE.ISO8859-15\nde_DE.8859"..., 4096) = 4096
read(18, "\t\t\t\ten_ZA.ISO8859-1\nen_ZA.88591."..., 4096) = 4096
read(18, "\t\t\t\t\t\teu_ES.ISO8859-1\neu_ES.iso8"..., 4096) = 4096
read(18, "iso88591\t\t\t\t\tgv_GB.ISO8859-1\ngv_"..., 4096) = 4096
read(18, "i\nkw\t\t\t\t\t\tkw_GB.ISO8859-1\nkw_GB\t"..., 4096) = 4096
read(18, "8859-15\nno@nynorsk\t\t\t\t\tny_NO.ISO"..., 4096) = 4096
read(18, "-8\nsr_YU@cyrillic\t\t\t\t\tsr_RS.UTF-"..., 4096) = 4096
read(18, "\t\t\tyi_US.CP1255\nyi_US.MICROSOFT-"..., 4096) = 4096
read(18, "d word is full locale name.\n#\n#\n"..., 4096) = 4096
read(18, "859-1\nbr_FR.iso88591:\t\t\t\t\tbr_FR."..., 4096) = 4096
read(18, "e_DE:\t\t\t\t\t\tde_DE.ISO8859-1\nde_DE"..., 4096) = 4096
close(18)                               = 0
openat(AT_FDCWD, "/usr/share/X11/locale/locale.dir", O_RDONLY) = 18
fstat(18, {st_mode=S_IFREG|0644, st_size=40629, ...}) = 0
read(18, "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"..., 4096) = 4096
read(18, "so8859-1/XLC_LOCALE\t\t\tes_CR.ISO8"..., 4096) = 4096
read(18, "/XLC_LOCALE\t\t\tno_NO.ISO8859-15\ni"..., 4096) = 4096
read(18, "\tas_IN.UTF-8\nen_US.UTF-8/XLC_LOC"..., 4096) = 4096
read(18, "OCALE\t\t\tku_TR.UTF-8\nen_US.UTF-8/"..., 4096) = 4096
read(18, ".ISO8859-6\niso8859-6/XLC_LOCALE:"..., 4096) = 4096
read(18, "SO8859-1\niso8859-1/XLC_LOCALE:\t\t"..., 4096) = 4096
read(18, "_LOCALE:\t\t\toc_FR.ISO8859-1\niso88"..., 4096) = 4096
read(18, ":\t\t\tbe_BY.UTF-8@latin\nen_US.UTF-"..., 4096) = 4096
close(18)                               = 0
access("/usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE", R_OK) = 0
openat(AT_FDCWD, "/usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE", O_RDONLY) = 18
fstat(18, {st_mode=S_IFREG|0644, st_size=4253, ...}) = 0
read(18, "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"..., 4096) = 4096
read(18, "\n}\n \n#\tcs20 class\ncs15\t{\n\tside\t\t"..., 4096) = 157
read(18, "", 4096)                      = 0
close(18)                               = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fce1db60140}, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fce1db60140}, 8) = 0
futex(0x7fce2053ae28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffffffef8b} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

Possibly similar to the bug for wxPython? https://github.com/wxWidgets/Phoenix/issues/648

**Comment by MrObvious** [comment]
Adding GDB:
paul@ubuntu:/etc/default$ gdb
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) run /opt/teams-for-linux/teams 
Starting program:  /opt/teams-for-linux/teams
No executable file specified.
Use the "file" or "exec-file" command.
(gdb) exec-file /opt/teams-for-linux/teams 
(gdb) run
Starting program: /opt/teams-for-linux/teams /opt/teams-for-linux/teams
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe85d2700 (LWP 18677)]

Thread 1 "teams" received signal SIGSEGV, Segmentation fault.
0x00000000020ff5fb in ?? ()
(gdb) bt
#0  0x00000000020ff5fb in  ()
#1  0x0000000000000040 in  ()
#2  0x000029bd7eae5258 in  ()
#3  0x0000000000000020 in  ()
#4  0x000029bd7eb88200 in  ()
#5  0x0000000000000020 in  ()
#6  0x000029bd7eae5000 in  ()
#7  0x000029bd7eb0c000 in  ()
#8  0x000029bd7eae52e8 in  ()
#9  0x000029bd7eb0cc00 in  ()
#10 0x0000000004a9cbb0 in  ()
#11 0x000029bd7eb82000 in  ()
#12 0x0000000000000017 in  ()
#13 0x000029bd7eb82000 in  ()
#14 0x0000000002100b98 in  ()
#15 0x000029bd7eb88000 in  ()
#16 0x0000000000000400 in  ()
#17 0x0000000003e72108 in  ()
#18 0x000029bd7eb0d800 in  ()
#19 0x0000000000000400 in  ()
#20 0x000029bd7eae5000 in  ()
#21 0x000029bd7eb0d800 in  ()
#22 0x000029bd7eb823f0 in  ()
#23 0x00007fffffffc7c0 in  ()
#24 0x00007fffffffc7d0 in  ()
#25 0x0000000003e72108 in  ()
#26 0x0000000000000140 in  ()
#27 0x000000000000107c in  ()
---Type <return> to continue, or q <return> to quit---
#28 0x000029bd7eae5000 in  ()
#29 0x0000000000000100 in  ()
#30 0x00000000020ff690 in  ()
#31 0x00007ffff7fa14f0 in  ()
#32 0x000029bd7eae5090 in  ()
#33 0x0000000000000020 in  ()
#34 0x000029bd7eb82030 in  ()
#35 0x0000000000000020 in  ()
#36 0x000029bd7eae5000 in  ()
#37 0x000029bd7eb82000 in  ()
#38 0x00000000020fbfd5 in  ()
#39 0x00007fffffffc824 in  ()
#40 0x00007ffff7ddf361 in do_lookup_x (undef_name=undef_name@entry=0x7ffff2e936c1 "strtol", new_hash=45893851553792, 
    new_hash@entry=479452909, old_hash=old_hash@entry=0x7fffffffc8f0, ref=0x7ffff2e89ff0, result=result@entry=0x7fffffffc900, scope=<optimized out>, i=<optimized out>, version=0x7ffff7f8fd30, flags=5, skip=<optimized out>, type_class=1, undef_map=0x7ffff7fa7000) at dl-lookup.c:558
#41 0x00007ffff7ddfee1 in _dl_lookup_symbol_x (undef_name=0x7ffff2e936c1 "strtol", undef_map=0x7ffff7fa7000, ref=ref@entry=0x7fffffffc9b8, symbol_scope=0x7ffff7fa7358, version=0x7ffff7f8fd30, type_class=type_class@entry=1, flags=5, skip_map=0x0) at dl-lookup.c:833
#42 0x00007ffff7de5234 in _dl_fixup (l=<optimized out>, reloc_arg=<optimized out>) at ../elf/dl-runtime.c:112
#43 0x00007ffff7ded647 in _dl_runtime_resolve_sse_vex () at ../sysdeps/x86_64/dl-trampoline.h:214
#44 0x00007fff00000000 in  ()
#45 0x000000000000005a in  ()
#46 0x00007fff00000000 in  ()
#47 0x000000000000005a in  ()
#48 0x0000000000000000 in  ()
(gdb)

**Comment by MrObvious** [comment]
Duplicate of https://github.com/electron/electron/issues/11234

Problem is upstream in Electron, and putting in workaround works.

**Comment by julian-alarcon** [comment]
Hi! Please check this fork and star it! https://github.com/IsmaelMartinez/teams-for-linux It is currently supported!

Maybe these issue is not there as new builds are already using newer electron version
