### ISSUE TITLE
ReferenceError: config is not defined

### ISSUE THREAD

**Issue by attila123** [ivelkov/teams-for-linux#49]
I pulled the latest code (master). I ran `npm install` earlier.
Trying to start it with `npm run`.
Dialog box appears 'Sign in to your account'. I click on my corporate account.
Then 'Taking you to your organization's sign in page' appears and in 1-2 sec an Error dialog is displayed:
```
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: config is not defined
    at App.<anonymous> (/opt/teams-for-linux/app/lib/index.js:89:3)
    at emitMany (events.js:151:20)
    at App.emit (events.js:223:7)
```
I also tried to do an `npm update`, did not help.
BTW it used to work both with `npm start` and from the AUR package (I'm on Arch Linux). Now it does not. Maybe MS changed something?
Node.js version in v8.9.4.

**Comment by jhult** [comment]
Maybe give this fork a try? It is more up-to-date: https://github.com/JamieMagee/teams-for-linux

**Comment by attila123** [comment]
@jhult Thanks for the suggestion. I tried that.
```
git clone https://github.com/JamieMagee/teams-for-linux.git
```
Installed yarn 1.10.0-1 (Arch Linux package).
```
avangel@t470:~/bin/teams-for-linux$ yarn start
yarn run v1.10.0
$ yarn install && yarn compile && electron ./app
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • no native production dependencies
$ rimraf 'app/**/*.js' && tsc
```
I even tried deleting ~/.config/teams-for-linux
What happens: I enter my email to the sign in dialog, click Next, and then 'Taking you to your organization's sign in page' appears, it just animates the dots, and does not proceed. :(
No error message is displayed anywhere (not in the gui, not in the console).

**Comment by IsmaelMartinez** [comment]
hi @attila123 , give a try this branch:
https://github.com/IsmaelMartinez/teams-for-linux

This project and the JamieMagee seem dead so, until they come back alive and I can merge back my changes, you can use and contribute in my branch.

**Comment by IsmaelMartinez** [comment]
@jhult , not sure if you can give JamieMagee a ping and see if he is back. Otherwise feel free to contribute. 
I will add a "credits" section as I don't want this to feel like a hijack

**Comment by attila123** [comment]
@IsmaelMartinez thank you very much, it works, you are the man! :)
